### ISSUE TITLE
Fix mobile layout

### ISSUE THREAD

**Issue by jabranr** [mrarslanark/mrarslanark.github.io#3]
Layout on mobile is broken. Make the layout responsive. Possibly try to use mobile-first approach and make use of media queries.

![image](https://user-images.githubusercontent.com/2131246/61944257-2eb34800-af95-11e9-8c5d-68357ad363f6.png)

**Comment by mraslanark** [comment]
It's a learning series which I am following, this design was implemented in the training series #1, now going for #2 which will focus on responsive design.

**Comment by mraslanark** [comment]
Kindly have a look and if the resume is responsive then kindly close the issue. Thanks

**Comment by jabranr** [comment]
Where is the pull request for it. You should make a pull request and link issues.

**Comment by jabranr** [comment]
If you make `padding: 15px` then top nav items will remain inline to each other on mobile too.

**Current**
![image](https://user-images.githubusercontent.com/2131246/62047451-71c62300-b202-11e9-8b96-82b6807f2b77.png)


**Expected**
![image](https://user-images.githubusercontent.com/2131246/62047425-59ee9f00-b202-11e9-888f-d3df6d045559.png)

**Comment by mrarslanark** [comment]
I've hidden the menu on smaller screen sizes.
